### ISSUE TITLE
Match summary

### ISSUE THREAD

**Issue by umer33511** [musa-1410/2023330_Stumps#2]
Batsman scores are segregated in match summary however bowler statistics are currently not being segregated according to team. Musa, kindly look into this

**Comment by musa-1410** [comment]
Sure I'll look into it.

**Comment by musa-1410** [comment]
It has been resolved and the working code has been pushed to the main branch.

**Comment by musa-1410** [comment]
It has been resolved and the working code has been pushed to the main branch.
